# Generated by Django 6.0.1 on 2026-01-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_budget_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='slug',
        ),
    ]
